version: '3.3'

volumes:
  inkledb:
    external: false

services:

  db:
    env_file: .env
    image: postgres
    volumes:
      - inkledb:/var/lib/postgresql/data/pgdata
      
  app:
    env_file: .env
    build: .
    image: inkewriter:0.1
    volumes:
        - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  

