test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: maxence
  db_password: strokes
  db_host:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

